### ISSUE TITLE
Add + Delete not working in PHP 7.4

### ISSUE THREAD

**Issue by mitesh21** [chetans9/core-php-admin-panel#37]
Hello,

This panel working fine on php 5.6.9. When i move code to php 7.4, it's showing many errors.

Fatal error: Uncaught Exception: Unknown column 'title, link, company_name, job_rel' in 'field list' query: INSERT INTO TABLE_NAME (`title, link, company_name, job_rel`) VALUES (?, ?, ?, ?) in /var/www/html/demo/Dashboard/lib/MysqliDb/MysqliDb.php:2008 Stack trace: #0 /var/www/html/demo/Dashboard/lib/MysqliDb/MysqliDb.php(1594): MysqliDb->_prepareQuery() #1 /var/www/html/demo/Dashboard/lib/MysqliDb/MysqliDb.php(1533): MysqliDb->_buildQuery() #2 /var/www/html/demo/Dashboard/lib/MysqliDb/MysqliDb.php(820): MysqliDb->_buildInsert() #3 /var/www/html/demo/Dashboard/add_new_job.php(18): MysqliDb->insert() #4 {main} thrown in /var/www/html/demo/Dashboard/lib/MysqliDb/MysqliDb.php on line 2008

**Comment by andrewc2** [comment]
For any future people coming across this, the MysqliDb library file needs to be updated to 2.9.3 and the issue is corrected. https://github.com/ThingEngineer/PHP-MySQLi-Database-Class/blob/master/MysqliDb.php
